import type { TeamAbbreviation } from '@mockingboard/shared';

/** Maps TeamAbbreviation to the Wikipedia template name used in staff pages. */
export const WIKI_TEAM_NAMES: Record<TeamAbbreviation, string> = {
  ARI: 'Arizona_Cardinals',
  ATL: 'Atlanta_Falcons',
  BAL: 'Baltimore_Ravens',
  BUF: 'Buffalo_Bills',
  CAR: 'Carolina_Panthers',
  CHI: 'Chicago_Bears',
  CIN: 'Cincinnati_Bengals',
  CLE: 'Cleveland_Browns',
  DAL: 'Dallas_Cowboys',
  DEN: 'Denver_Broncos',
  DET: 'Detroit_Lions',
  GB: 'Green_Bay_Packers',
  HOU: 'Houston_Texans',
  IND: 'Indianapolis_Colts',
  JAX: 'Jacksonville_Jaguars',
  KC: 'Kansas_City_Chiefs',
  LAC: 'Los_Angeles_Chargers',
  LAR: 'Los_Angeles_Rams',
  LV: 'Las_Vegas_Raiders',
  MIA: 'Miami_Dolphins',
  MIN: 'Minnesota_Vikings',
  NE: 'New_England_Patriots',
  NO: 'New_Orleans_Saints',
  NYG: 'New_York_Giants',
  NYJ: 'New_York_Jets',
  PHI: 'Philadelphia_Eagles',
  PIT: 'Pittsburgh_Steelers',
  SEA: 'Seattle_Seahawks',
  SF: 'San_Francisco_49ers',
  TB: 'Tampa_Bay_Buccaneers',
  TEN: 'Tennessee_Titans',
  WAS: 'Washington_Commanders',
};
