import type { TeamAbbreviation } from '@mockingboard/shared';

/** Maps TeamAbbreviation to the URL slug used by Over The Cap. */
export const OTC_TEAM_SLUGS: Record<TeamAbbreviation, string> = {
  ARI: 'arizona-cardinals',
  ATL: 'atlanta-falcons',
  BAL: 'baltimore-ravens',
  BUF: 'buffalo-bills',
  CAR: 'carolina-panthers',
  CHI: 'chicago-bears',
  CIN: 'cincinnati-bengals',
  CLE: 'cleveland-browns',
  DAL: 'dallas-cowboys',
  DEN: 'denver-broncos',
  DET: 'detroit-lions',
  GB: 'green-bay-packers',
  HOU: 'houston-texans',
  IND: 'indianapolis-colts',
  JAX: 'jacksonville-jaguars',
  KC: 'kansas-city-chiefs',
  LAC: 'los-angeles-chargers',
  LAR: 'los-angeles-rams',
  LV: 'las-vegas-raiders',
  MIA: 'miami-dolphins',
  MIN: 'minnesota-vikings',
  NE: 'new-england-patriots',
  NO: 'new-orleans-saints',
  NYG: 'new-york-giants',
  NYJ: 'new-york-jets',
  PHI: 'philadelphia-eagles',
  PIT: 'pittsburgh-steelers',
  SEA: 'seattle-seahawks',
  SF: 'san-francisco-49ers',
  TB: 'tampa-bay-buccaneers',
  TEN: 'tennessee-titans',
  WAS: 'washington-commanders',
};

/** Reverse lookup: OTC team mascot name to TeamAbbreviation. */
export const OTC_NAME_TO_ABBR: Record<string, TeamAbbreviation> = {
  Cardinals: 'ARI',
  Falcons: 'ATL',
  Ravens: 'BAL',
  Bills: 'BUF',
  Panthers: 'CAR',
  Bears: 'CHI',
  Bengals: 'CIN',
  Browns: 'CLE',
  Cowboys: 'DAL',
  Broncos: 'DEN',
  Lions: 'DET',
  Packers: 'GB',
  Texans: 'HOU',
  Colts: 'IND',
  Jaguars: 'JAX',
  Chiefs: 'KC',
  Chargers: 'LAC',
  Rams: 'LAR',
  Raiders: 'LV',
  Dolphins: 'MIA',
  Vikings: 'MIN',
  Patriots: 'NE',
  Saints: 'NO',
  Giants: 'NYG',
  Jets: 'NYJ',
  Eagles: 'PHI',
  Steelers: 'PIT',
  Seahawks: 'SEA',
  '49ers': 'SF',
  Buccaneers: 'TB',
  Titans: 'TEN',
  Commanders: 'WAS',
};
