import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { Player } from '@mockingboard/shared';

export type PdfDepth = 'skim' | 'peruse' | 'deep-dive';

interface DraftGuidePdfProps {
  boardName: string;
  authorName?: string;
  year: number;
  players: Player[];
  depth: PdfDepth;
}

const POS_COLORS: Record<string, string> = {
  QB: '#e74c3c',
  RB: '#27ae60',
  WR: '#f39c12',
  TE: '#8e44ad',
  OT: '#2980b9',
  OG: '#2980b9',
  C: '#2980b9',
  EDGE: '#d35400',
  DL: '#c0392b',
  LB: '#16a085',
  CB: '#2c3e50',
  S: '#7f8c8d',
};

const s = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: '#1a1a1a',
  },
  // Cover
  coverPage: {
    padding: 40,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  coverTitle: {
    fontSize: 36,
    fontFamily: 'Helvetica-Bold',
    textAlign: 'center',
    marginBottom: 12,
  },
  coverSubtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 6,
  },
  coverYear: {
    fontSize: 48,
    fontFamily: 'Helvetica-Bold',
    color: '#e74c3c',
    marginBottom: 40,
  },
  coverBrand: {
    fontSize: 12,
    color: '#999',
    marginTop: 'auto',
    textAlign: 'center',
  },
  // Header
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottom: '1 solid #ddd',
    paddingBottom: 8,
    marginBottom: 16,
  },
  headerTitle: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
  },
  headerRight: {
    fontSize: 8,
    color: '#999',
  },
  // Footer
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 8,
    color: '#999',
  },
  // Skim table
  tableHeader: {
    flexDirection: 'row',
    borderBottom: '1 solid #333',
    paddingBottom: 4,
    marginBottom: 4,
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: '#666',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 3,
    borderBottom: '0.5 solid #eee',
  },
  colRank: { width: 30 },
  colName: { width: 160, fontFamily: 'Helvetica-Bold' },
  colPos: { width: 40 },
  colSchool: { width: 120 },
  colHtWt: { width: 70 },
  colComp: { width: 120 },
  posBadge: {
    fontSize: 8,
    color: '#fff',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 2,
  },
  // Peruse additions
  tags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 3,
    marginTop: 2,
  },
  tag: {
    fontSize: 7,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 2,
    backgroundColor: '#f0f0f0',
    color: '#555',
  },
  strengthTag: { backgroundColor: '#d4edda', color: '#155724' },
  weaknessTag: { backgroundColor: '#f8d7da', color: '#721c24' },
  // Deep dive
  playerCard: {
    marginBottom: 16,
    border: '1 solid #ddd',
    borderRadius: 4,
    padding: 12,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingBottom: 6,
    borderBottom: '0.5 solid #eee',
  },
  cardName: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
  },
  cardMeta: {
    fontSize: 9,
    color: '#666',
  },
  sectionLabel: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: '#666',
    marginBottom: 2,
    marginTop: 8,
  },
  summaryText: {
    fontSize: 9,
    lineHeight: 1.4,
    color: '#333',
  },
  measurablesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  measurable: {
    fontSize: 8,
    color: '#555',
  },
  measurableValue: {
    fontFamily: 'Helvetica-Bold',
    color: '#1a1a1a',
  },
});

function formatHeight(inches?: number): string {
  if (!inches) return '';
  const ft = Math.floor(inches / 12);
  const rem = inches % 12;
  return `${ft}'${rem}"`;
}

export function DraftGuidePdf({
  boardName,
  authorName,
  year,
  players,
  depth,
}: DraftGuidePdfProps) {
  return (
    <Document title={`${boardName} - ${year} Draft Guide`} author={authorName}>
      {/* Cover page */}
      <Page size="LETTER" style={s.coverPage}>
        <Text style={s.coverYear}>{year}</Text>
        <Text style={s.coverTitle}>{boardName}</Text>
        {authorName && <Text style={s.coverSubtitle}>by {authorName}</Text>}
        <Text style={s.coverSubtitle}>
          {players.length} Prospect{players.length !== 1 ? 's' : ''}
          {' \u2022 '}
          {depth === 'skim'
            ? 'Quick Look'
            : depth === 'peruse'
              ? 'Detailed'
              : 'Full Breakdown'}
        </Text>
        <Text style={s.coverBrand}>Generated by MockingBoard</Text>
      </Page>

      {/* Content pages */}
      {depth === 'deep-dive' ? (
        <DeepDivePages players={players} boardName={boardName} year={year} />
      ) : (
        <TablePages
          players={players}
          boardName={boardName}
          year={year}
          depth={depth}
        />
      )}
    </Document>
  );
}

function PageFooter() {
  return (
    <View style={s.footer} fixed>
      <Text>Generated by MockingBoard</Text>
      <Text
        render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
      />
    </View>
  );
}

function PageHeader({ boardName, year }: { boardName: string; year: number }) {
  return (
    <View style={s.header} fixed>
      <Text style={s.headerTitle}>{boardName}</Text>
      <Text style={s.headerRight}>{year} Draft Guide</Text>
    </View>
  );
}

function PosBadge({ position }: { position: string }) {
  const bg = POS_COLORS[position] ?? '#999';
  return <Text style={[s.posBadge, { backgroundColor: bg }]}>{position}</Text>;
}

function TablePages({
  players,
  boardName,
  year,
  depth,
}: {
  players: Player[];
  boardName: string;
  year: number;
  depth: 'skim' | 'peruse';
}) {
  const isPeruse = depth === 'peruse';

  return (
    <Page size="LETTER" style={s.page} wrap>
      <PageHeader boardName={boardName} year={year} />

      <View style={s.tableHeader}>
        <Text style={s.colRank}>#</Text>
        <Text style={s.colName}>Player</Text>
        <Text style={s.colPos}>Pos</Text>
        <Text style={s.colSchool}>School</Text>
        {isPeruse && <Text style={s.colHtWt}>Ht/Wt</Text>}
        {isPeruse && <Text style={s.colComp}>NFL Comp</Text>}
      </View>

      {players.map((player, i) => (
        <View key={player.id} style={s.tableRow} wrap={false}>
          <Text style={s.colRank}>{i + 1}</Text>
          <View style={s.colName}>
            <Text>{player.name}</Text>
            {isPeruse && player.scouting?.strengths && (
              <View style={s.tags}>
                {player.scouting.strengths.slice(0, 3).map((str) => (
                  <Text key={str} style={[s.tag, s.strengthTag]}>
                    {str}
                  </Text>
                ))}
                {player.scouting.weaknesses?.slice(0, 2).map((w) => (
                  <Text key={w} style={[s.tag, s.weaknessTag]}>
                    {w}
                  </Text>
                ))}
              </View>
            )}
          </View>
          <View style={s.colPos}>
            <PosBadge position={player.position} />
          </View>
          <Text style={s.colSchool}>{player.school}</Text>
          {isPeruse && (
            <Text style={s.colHtWt}>
              {formatHeight(player.attributes?.height)}
              {player.attributes?.weight
                ? ` / ${player.attributes.weight}`
                : ''}
            </Text>
          )}
          {isPeruse && (
            <Text style={s.colComp}>{player.scouting?.comparison ?? ''}</Text>
          )}
        </View>
      ))}

      <PageFooter />
    </Page>
  );
}

function DeepDivePages({
  players,
  boardName,
  year,
}: {
  players: Player[];
  boardName: string;
  year: number;
}) {
  return (
    <Page size="LETTER" style={s.page} wrap>
      <PageHeader boardName={boardName} year={year} />

      {players.map((player, i) => (
        <View key={player.id} style={s.playerCard} wrap={false}>
          <View style={s.cardHeader}>
            <View>
              <Text style={s.cardName}>
                {i + 1}. {player.name}
              </Text>
              <Text style={s.cardMeta}>
                {player.position} \u2022 {player.school}
                {player.attributes?.conference
                  ? ` \u2022 ${player.attributes.conference}`
                  : ''}
              </Text>
            </View>
            <PosBadge position={player.position} />
          </View>

          {/* Measurables */}
          {player.attributes && (
            <>
              <Text style={s.sectionLabel}>MEASURABLES</Text>
              <View style={s.measurablesRow}>
                {player.attributes.height && (
                  <Text style={s.measurable}>
                    Height:{' '}
                    <Text style={s.measurableValue}>
                      {formatHeight(player.attributes.height)}
                    </Text>
                  </Text>
                )}
                {player.attributes.weight && (
                  <Text style={s.measurable}>
                    Weight:{' '}
                    <Text style={s.measurableValue}>
                      {player.attributes.weight} lbs
                    </Text>
                  </Text>
                )}
                {player.attributes.fortyYard && (
                  <Text style={s.measurable}>
                    40-Yard:{' '}
                    <Text style={s.measurableValue}>
                      {player.attributes.fortyYard}s
                    </Text>
                  </Text>
                )}
                {player.attributes.vertical && (
                  <Text style={s.measurable}>
                    Vertical:{' '}
                    <Text style={s.measurableValue}>
                      {player.attributes.vertical}&quot;
                    </Text>
                  </Text>
                )}
                {player.attributes.broad && (
                  <Text style={s.measurable}>
                    Broad:{' '}
                    <Text style={s.measurableValue}>
                      {player.attributes.broad}&quot;
                    </Text>
                  </Text>
                )}
                {player.attributes.bench && (
                  <Text style={s.measurable}>
                    Bench:{' '}
                    <Text style={s.measurableValue}>
                      {player.attributes.bench}
                    </Text>
                  </Text>
                )}
              </View>
            </>
          )}

          {/* NFL Comparison */}
          {player.scouting?.comparison && (
            <>
              <Text style={s.sectionLabel}>NFL COMPARISON</Text>
              <Text style={s.summaryText}>{player.scouting.comparison}</Text>
            </>
          )}

          {/* Scouting Summary */}
          {player.scouting?.summary && (
            <>
              <Text style={s.sectionLabel}>SCOUTING SUMMARY</Text>
              <Text style={s.summaryText}>{player.scouting.summary}</Text>
            </>
          )}

          {/* Strengths & Weaknesses */}
          {player.scouting?.strengths &&
            player.scouting.strengths.length > 0 && (
              <>
                <Text style={s.sectionLabel}>STRENGTHS</Text>
                <View style={s.tags}>
                  {player.scouting.strengths.map((str) => (
                    <Text key={str} style={[s.tag, s.strengthTag]}>
                      {str}
                    </Text>
                  ))}
                </View>
              </>
            )}
          {player.scouting?.weaknesses &&
            player.scouting.weaknesses.length > 0 && (
              <>
                <Text style={s.sectionLabel}>WEAKNESSES</Text>
                <View style={s.tags}>
                  {player.scouting.weaknesses.map((w) => (
                    <Text key={w} style={[s.tag, s.weaknessTag]}>
                      {w}
                    </Text>
                  ))}
                </View>
              </>
            )}
        </View>
      ))}

      <PageFooter />
    </Page>
  );
}
